name: invoice_generator
description: "A Flutter project for invoice generation ."
publish_to: "none"

version: 0.6.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: 2.6.1
  file_picker: 8.1.7
  intl: 0.19.0
  lottie: 3.1.3
  pdf: 3.11.3
  printing: 5.14.2
  auto_size_text: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: 2.4.13
  freezed: 2.5.1
  riverpod_generator: 2.6.3
  json_serializable: 6.7.1
  riverpod_annotation: 2.6.1
  freezed_annotation: 2.4.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/lottie/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
